item {
  display_name: 'Bicycles_and_pedestrians_only'
  id: 1
  name: 'Bicycles_and_pedestrians_only'
}
item {
  display_name: 'Bicycles_only'
  id: 2
  name: 'Bicycles_only'
}
item {
  display_name: 'Bumpy_road'
  id: 3
  name: 'Bumpy_road'
}
item {
  display_name: 'Buses_priority'
  id: 4
  name: 'Buses_priority'
}
item {
  display_name: 'Center_line'
  id: 5
  name: 'Center_line'
}
item {
  display_name: 'Closed_to_pedestrians'
  id: 6
  name: 'Closed_to_pedestrians'
}
item {
  display_name: 'Crossroads'
  id: 7
  name: 'Crossroads'
}
item {
  display_name: 'Dangerous_wind_gusts'
  id: 8
  name: 'Dangerous_wind_gusts'
}
item {
  display_name: 'Directions_indicator'
  id: 9
  name: 'Directions_indicator'
}
item {
  display_name: 'End_of_restriction'
  id: 10
  name: 'End_of_restriction'
}
item {
  display_name: 'Falling_rocks'
  id: 11
  name: 'Falling_rocks'
}
item {
  display_name: 'Go_straight'
  id: 12
  name: 'Go_straight'
}
item {
  display_name: 'Keep_left'
  id: 13
  name: 'Keep_left'
}
item {
  display_name: 'Keep_right'
  id: 14
  name: 'Keep_right'
}
item {
  display_name: 'Left_curve'
  id: 15
  name: 'Left_curve'
}
item {
  display_name: 'Left_lane_ends'
  id: 16
  name: 'Left_lane_ends'
}
item {
  display_name: 'Left_turn'
  id: 17
  name: 'Left_turn'
}
item {
  display_name: 'Maximum_speed_limit30km'
  id: 18
  name: 'Maximum_speed_limit30km'
}
item {
  display_name: 'Maximum_speed_limit40km'
  id: 19
  name: 'Maximum_speed_limit40km'
}
item {
  display_name: 'Maximum_speed_limit50km'
  id: 20
  name: 'Maximum_speed_limit50km'
}
item {
  display_name: 'Maximum_speed_limit60km'
  id: 21
  name: 'Maximum_speed_limit60km'
}
item {
  display_name: 'Maximum_speed_limit70km'
  id: 22
  name: 'Maximum_speed_limit70km'
}
item {
  display_name: 'Maximum_speed_limit80km'
  id: 23
  name: 'Maximum_speed_limit80km'
}
item {
  display_name: 'Maximum_speed_limit90km'
  id: 24
  name: 'Maximum_speed_limit90km'
}
item {
  display_name: 'Merging_traffic_ahead'
  id: 25
  name: 'Merging_traffic_ahead'
}
item {
  display_name: 'Minimum_speed_limit30km'
  id: 26
  name: 'Minimum_speed_limit30km'
}
item {
  display_name: 'Minimum_speed_limit50km'
  id: 27
  name: 'Minimum_speed_limit50km'
}
item {
  display_name: 'No_bicycles'
  id: 28
  name: 'No_bicycles'
}
item {
  display_name: 'No_buses'
  id: 29
  name: 'No_buses'
}
item {
  display_name: 'No_entry_for_vehicles'
  id: 30
  name: 'No_entry_for_vehicles'
}
item {
  display_name: 'No_large_trucks'
  id: 31
  name: 'No_large_trucks'
}
item {
  display_name: 'No_motorless_vehicle_except_bicycle'
  id: 32
  name: 'No_motorless_vehicle_except_bicycle'
}
item {
  display_name: 'No_overtaking'
  id: 33
  name: 'No_overtaking'
}
item {
  display_name: 'No_pedestrian_crossing'
  id: 34
  name: 'No_pedestrian_crossing'
}
item {
  display_name: 'No_right_turn_crossing'
  id: 35
  name: 'No_right_turn_crossing'
}
item {
  display_name: 'No_stopping'
  id: 36
  name: 'No_stopping'
}
item {
  display_name: 'No_twoperson_motorcycles'
  id: 37
  name: 'No_twoperson_motorcycles'
}
item {
  display_name: 'No_two_stage_right_turn_for_mopeds'
  id: 38
  name: 'No_two_stage_right_turn_for_mopeds'
}
item {
  display_name: 'No_u_turns'
  id: 39
  name: 'No_u_turns'
}
item {
  display_name: 'No_vehicles_carrying_dangerous_goods'
  id: 40
  name: 'No_vehicles_carrying_dangerous_goods'
}
item {
  display_name: 'No_vehicles_except_motorcycles'
  id: 41
  name: 'No_vehicles_except_motorcycles'
}
item {
  display_name: 'No_vehicles_higher_than3.3ms'
  id: 42
  name: 'No_vehicles_higher_than3.3ms'
}
item {
  display_name: 'No_vehicles_weighing_over5.5ts'
  id: 43
  name: 'No_vehicles_weighing_over5.5ts'
}
item {
  display_name: 'No_vehicles_wider_than2.2ms'
  id: 44
  name: 'No_vehicles_wider_than2.2ms'
}
item {
  display_name: 'No_waiting'
  id: 45
  name: 'No_waiting'
}
item {
  display_name: 'One_way'
  id: 46
  name: 'One_way'
}
item {
  display_name: 'One_way_to_the_left'
  id: 47
  name: 'One_way_to_the_left'
}
item {
  display_name: 'One_way_to_the_right'
  id: 48
  name: 'One_way_to_the_right'
}
item {
  display_name: 'Other_dangers'
  id: 49
  name: 'Other_dangers'
}
item {
  display_name: 'Parking_allowed'
  id: 50
  name: 'Parking_allowed'
}
item {
  display_name: 'Pedesrtrian_crossing'
  id: 51
  name: 'Pedesrtrian_crossing'
}
item {
  display_name: 'Pedestrians_only'
  id: 52
  name: 'Pedestrians_only'
}
item {
  display_name: 'Restricted_parking'
  id: 53
  name: 'Restricted_parking'
}
item {
  display_name: 'Restricted_zone'
  id: 54
  name: 'Restricted_zone'
}
item {
  display_name: 'Restriction_begins'
  id: 55
  name: 'Restriction_begins'
}
item {
  display_name: 'Restriction_ends'
  id: 56
  name: 'Restriction_ends'
}
item {
  display_name: 'Right_curve'
  id: 57
  name: 'Right_curve'
}
item {
  display_name: 'Right_turn'
  id: 58
  name: 'Right_turn'
}
item {
  display_name: 'Roadworks'
  id: 59
  name: 'Roadworks'
}
item {
  display_name: 'Road_closed_to_all'
  id: 60
  name: 'Road_closed_to_all'
}
item {
  display_name: 'Road_closed_to_vehicles'
  id: 61
  name: 'Road_closed_to_vehicles'
}
item {
  display_name: 'Road_narrows'
  id: 62
  name: 'Road_narrows'
}
item {
  display_name: 'Rotary'
  id: 63
  name: 'Rotary'
}
item {
  display_name: 'Roundabout'
  id: 64
  name: 'Roundabout'
}
item {
  display_name: 'Safety_zone'
  id: 65
  name: 'Safety_zone'
}
item {
  display_name: 'School_crossing'
  id: 66
  name: 'School_crossing'
}
item {
  display_name: 'School_zone'
  id: 67
  name: 'School_zone'
}
item {
  display_name: 'Series_of_curves_to_the_left'
  id: 68
  name: 'Series_of_curves_to_the_left'
}
item {
  display_name: 'Series_of_curves_to_the_right'
  id: 69
  name: 'Series_of_curves_to_the_right'
}
item {
  display_name: 'Slippery_road'
  id: 70
  name: 'Slippery_road'
}
item {
  display_name: 'Slow_down'
  id: 71
  name: 'Slow_down'
}
item {
  display_name: 'Sound_horn'
  id: 72
  name: 'Sound_horn'
}
item {
  display_name: 'Steep_ascent10%'
  id: 73
  name: 'Steep_ascent10%'
}
item {
  display_name: 'Steep_descent10%'
  id: 74
  name: 'Steep_descent10%'
}
item {
  display_name: 'Stop'
  id: 75
  name: 'Stop'
}
item {
  display_name: 'Stopping_allowed'
  id: 76
  name: 'Stopping_allowed'
}
item {
  display_name: 'Stop_line'
  id: 77
  name: 'Stop_line'
}
item {
  display_name: 'Straight_ahead_or_left_turn'
  id: 78
  name: 'Straight_ahead_or_left_turn'
}
item {
  display_name: 'Straight_ahead_or_right_turn'
  id: 79
  name: 'Straight_ahead_or_right_turn'
}
item {
  display_name: 'Traffic_light_ahead'
  id: 80
  name: 'Traffic_light_ahead'
}
item {
  display_name: 'Train_crossing'
  id: 81
  name: 'Train_crossing'
}
item {
  display_name: 'Turn_left'
  id: 82
  name: 'Turn_left'
}
item {
  display_name: 'Turn_left_or_right'
  id: 83
  name: 'Turn_left_or_right'
}
item {
  display_name: 'Turn_right'
  id: 84
  name: 'Turn_right'
}
item {
  display_name: 'Two_stage_right_turn_for_mopeds'
  id: 85
  name: 'Two_stage_right_turn_for_mopeds'
}
item {
  display_name: 'Two_way_traffic_ahead'
  id: 86
  name: 'Two_way_traffic_ahead'
}
item {
  display_name: 'T_junction'
  id: 87
  name: 'T_junction'
}
item {
  display_name: 'Vehicles_only'
  id: 88
  name: 'Vehicles_only'
}
item {
  display_name: 'Wild_animals_crossing'
  id: 89
  name: 'Wild_animals_crossing'
}
item {
  display_name: 'Y_junction'
  id: 90
  name: 'Y_junction'
}
